MSVC: Allows building C examples
There is no C99 support with MSVC, we have to compile C sources
with C++ compiler, and thus make some adjustments.

Also fix common problem on MSVC:
 error C2668: 'sqrt' : ambiguous call to overloaded function