Fix missing template parameters on old compilers
  In file included from .../src/default_engine.hpp:25,
                   from .../src/default_engine.cpp:23:
  .../src/h_matrix.hpp: In member function 'hmat::HMatrix<T>* hmat::HMatrix<T>::getChild(int) const':
  .../src/h_matrix.hpp:468: error: 'template<int N> class hmat::Tree' used without template parameters
  .../src/h_matrix.hpp: In member function 'hmat::HMatrix<T>* hmat::HMatrix<T>::get(int, int) const':
  .../src/h_matrix.hpp:480: error: 'template<int N> class hmat::Tree' used without template parameters
  .../src/h_matrix.hpp: In member function 'void hmat::HMatrix<T>::insertChild(int, hmat::HMatrix<T>*)':
  .../src/h_matrix.hpp:491: error: 'template<int N> class hmat::Tree' used without template parameters
  .../src/h_matrix.hpp: In member function 'void hmat::HMatrix<T>::insertChild(int, int, hmat::HMatrix<T>*)':