Fix build failures with clang
  .../src/assembly.hpp:75:34: error: deleting pointer to incomplete type
  'const hmat::CompressionAlgorithm' may cause undefined behavior
  [-Werror,-Wdelete-incomplete]