Fix compilation with older OSX compilers
It seems that compilations on conda fails because OSX compiler
installed there have unordered_map in tr1; thus build fails
if -std=c++11 option is passed.
But if this option is omitted, compiler complains:

  .../examples/cylinder.cpp:127:10: error: no matching member function for call to 'real'
  result.real(cos(k * distance) / (4 * M_PI * distance));

  ~~~~~~~^~~~

Replace this C++11 function by a standard constructor.