rk_matrix: workaround gcc12 uninitialized warning
Seems like a false positive because alphaV is always entirely initialized:

rk_matrix.cpp:1035:22: error: ‘<unknown>’ may be used uninitialized [-Werror=maybe-uninitialized]
 1035 |     formattedAddParts(epsilon, alphaV, subRks, nSubRks);
      |     ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/io/src/rk_matrix.cpp:501:6: note: by argument 3 of type ‘const double*’ to ‘void hmat::RkMatrix<T>::formattedAddParts(double, const T*, const hmat::RkMatrix<T>* const*, int, bool) [with T = double]’ declared here
  501 | void RkMatrix<T>::formattedAddParts(double epsilon, const T* alpha, const RkMatrix<T>* const * parts,
      |      ^~~~~~~~~~~

Nevetherless it may be still be better to use the std::vector ctor instead of a
variable length array in combination with fill_n.