Fix a -Wdeprecated-copy-with-user-provided-copy with clang 20
The full message is:
error: definition of implicit copy assignment operator for 'ClusterData'
is deprecated because it has a user-provided copy constructor

This happen because define a copy constructor without defining a copy
operator. We remove the custom copy contructor because it does the same
as the default one.